version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: crm-vendas-mongo
    environment:
      MONGO_INITDB_DATABASE: crm-vendas
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
